src/AffiliateDashboardBundle/Entity/User.php
<?php

namespace AffiliateDashboardBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AffiliateDashboardBundle\Repository\UserRepository")
 */
class User
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="BlogpostUser", mappedBy="user", cascade={"all"})
     */
    private $blogpostUser;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Payment" , mappedBy="user" , cascade={"all"})
     */
    private $payments;

    function __construct()
    {
        $this->blogpostUser = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    /**
     * @return string
     */
    function __toString()
    {
        return $this->getName();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return BlogpostUser[]
     */
    public function getBlogpostUser()
    {
        return $this->blogpostUser;
    }

    /**
     * @param Payment $payment
     * @return $this
     */
    public function addPayment(Payment $payment)
    {
        $this->payments->add($payment);

        return $this;
    }

    /**
     * @return Payment[]
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * @param Payment[] $payments
     */
    public function setPayments($payments)
    {
        $this->payments = $payments;
    }

    /**
     * @return float
     */
    public function getEarnings()
    {
        $sum = 0;

        foreach ($this->getBlogpostUser() as $bu) {
            $tag = $bu->getBlogpost()->getAffiliateTag();
            $sum += $tag->getEarnings() / count($tag->getBlogposts()) / 100 * $bu->getPercentage();
        }

        return $sum;
    }

    public function getPaid()
    {
        $sum = 0;

        foreach ($this->getPayments() as $payment) {
            $sum += $payment->getAmount();
        }

        return $sum;
    }
}

src/AffiliateDashboardBundle/Form/UserType.php
<?php

namespace AffiliateDashboardBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('email')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AffiliateDashboardBundle\Entity\User'
        ));
    }
}

src/AffiliateDashboardBundle/Controller/UserController.php
<?php

namespace AffiliateDashboardBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use AffiliateDashboardBundle\Entity\User;
use AffiliateDashboardBundle\Form\UserType;

/**
 * User controller.
 *
 * @Route("/{_locale}/user")
 */
class UserController extends Controller
{
    /**
     * Lists all User entities.
     *
     * @Route("/", name="user_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $users = $em->getRepository('AffiliateDashboardBundle:User')->findAll();

        return $this->render(
            'AffiliateDashboardBundle:User:index.html.twig',
            array(
                'users' => $users,
            )
        );
    }

    /**
     * Creates a new User entity.
     *
     * @Route("/new", name="user_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $user = new User();
        $form = $this->createForm('AffiliateDashboardBundle\Form\UserType', $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render(
            'AffiliateDashboardBundle:User:new.html.twig',
            array(
                'user' => $user,
                'form' => $form->createView(),
            )
        );
    }

    /**
     * Displays a form to edit an existing User entity.
     *
     * @Route("/{id}/edit", name="user_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, User $user)
    {
        $deleteForm = $this->createDeleteForm($user);
        $editForm = $this->createForm('AffiliateDashboardBundle\Form\UserType', $user);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render(
            'AffiliateDashboardBundle:User:edit.html.twig',
            array(
                'user' => $user,
                'edit_form' => $editForm->createView(),
                'delete_form' => $deleteForm->createView(),
            )
        );
    }

    /**
     * Deletes a User entity.
     *
     * @Route("/{id}", name="user_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, User $user)
    {
        $form = $this->createDeleteForm($user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($user);
            $em->flush();
        }

        return $this->redirectToRoute('user_index');
    }

    /**
     * Creates a form to delete a User entity.
     *
     * @param User $user The User entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(User $user)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('user_delete', array('id' => $user->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/AffiliateDashboardBundle/Resources/views/User/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1>{% trans %}Edit User{% endtrans %}</h1>
    </div>

    {{ form_start(edit_form, { 'style': 'horizontal' }) }}
        {{ form_widget(edit_form) }}

        <p>
            <input type="submit" value="{% trans %}save{% endtrans %}" class="btn btn-primary" />
        </p>

    {{ form_end(edit_form) }}

    <p>
        {{ form_start(delete_form) }}
            <input type="submit" value="{% trans %}delete{% endtrans %}" class="btn btn-danger" />
        {{ form_end(delete_form) }}
    </p>

    <p>
        <a class="btn btn-default btn-xs" href="{{ path('user_index') }}">{% trans %}back to the list{% endtrans %}</a>
    </p>
{% endblock %}

src/AffiliateDashboardBundle/Resources/views/User/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1>{% trans %}Users{% endtrans %}</h1>
    </div>

    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>{% trans %}Name{% endtrans %}</th>
                <th>{% trans %}Email{% endtrans %}</th>
                <th>{% trans %}Sales{% endtrans %}</th>
                <th>{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <span class="label label-default">{{ user.blogpostUser|length }} {% trans %}Blogposts{% endtrans %}</span><br/>
                    <span class="label label-warning">{{ user.earnings|localizedcurrency('EUR') }} {% trans %}earned{% endtrans %}</span><br/>
                    <span class="label label-success">{{ user.paid|localizedcurrency('EUR') }} {% trans %}paid{% endtrans %}</span><br/>
                    <span class="label label-danger">{{ (user.earnings - user.paid)|localizedcurrency('EUR') }} {% trans %}open{% endtrans %}</span>
                </td>
                <td>
                    <a class="btn btn-info btn-sm" href="{{ path('user_edit', { 'id': user.id }) }}">{% trans %}edit{% endtrans %}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/AffiliateDashboardBundle/Resources/views/User/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1>{% trans %}Create User{% endtrans %}</h1>
    </div>

    {{ form_start(form, { 'style': 'horizontal' }) }}
        {{ form_widget(form) }}

        <p>
            <input type="submit" value="{% trans %}create{% endtrans %}" class="btn btn-primary" />
        </p>
    {{ form_end(form) }}

    <p>
        <a class="btn btn-default btn-xs" href="{{ path('user_index') }}">{% trans %}back to the list{% endtrans %}</a>
    </p>
{% endblock %}